In [2]:
from mmdet.apis import init_detector, inference_detector, show_result_pyplot
import mmcv
from dbscan_result_to_aligned_result import dbscan_result_to_aligned_result
from algo2_result_to_aligned_result import algo2_result_to_aligned_result

In [3]:
config_file = '/home/aiarhipov/centernet/exps/19_eval/config.py'
checkpoint_file = '/home/aiarhipov/centernet/exps/19_eval/epoch60_resnet34_batch2.pth'
model = init_detector(config_file, checkpoint_file, device='cuda:0')
img_path = '/home/aiarhipov/centernet/imgs/0d60a677b078409f89cb85cd518f196fb77a6e07.jpg'  # or img = mmcv.imread(img), which will only load it once
res = inference_detector(model, img_path)
res1 = res
threshold = 0.5
show_result_pyplot(model, img_path, res, score_thr = threshold, out_file = "/home/aiarhipov/centernet/imgs/output.jpg")
res_algo2 = algo2_result_to_aligned_result(res1, threshold=threshold, r=0.2)
res_dbscan = dbscan_result_to_aligned_result(res1, threshold=threshold)
_res_algo2 = res_algo2
_res_dbscan = res_dbscan
show_result_pyplot(model, img_path, _res_algo2, score_thr = threshold, out_file = "/home/aiarhipov/centernet/imgs/output_algo2.jpg")
show_result_pyplot(model, img_path, _res_dbscan, score_thr = threshold, out_file = "/home/aiarhipov/centernet/imgs/output_dbscan.jpg")

load checkpoint from local path: /home/aiarhipov/centernet/exps/19_eval/epoch60_resnet34_batch2.pth


2023-04-18 14:30:17,124 - root - INFO - ModulatedDeformConvPack neck.deconv_layers.0.conv is upgraded to version 2.
2023-04-18 14:30:17,127 - root - INFO - ModulatedDeformConvPack neck.deconv_layers.2.conv is upgraded to version 2.
2023-04-18 14:30:17,129 - root - INFO - ModulatedDeformConvPack neck.deconv_layers.4.conv is upgraded to version 2.


keep_x = [561.35297, 560.5673],  mean = 560 
keep_y = [376.86996, 375.275],  mean = 376 
idx_i_j =  [64, 0]
vertex_idx =  [1, 0]
####################################################################################################
(117, 5)
keep_x = [727.3515, 729.2243],  mean = 728 
keep_y = [375.5371, 375.275],  mean = 375 
idx_i_j =  [2, 0]
vertex_idx =  [0, 1]
####################################################################################################
(117, 5)
keep_x = [728.0, 730.36926, 729.6365, 729.2243],  mean = 729 
keep_y = [469.0027, 468.04575, 468.68292, 469.83273],  mean = 468 
idx_i_j =  [2, 110, 112, 0]
vertex_idx =  [3, 0, 1, 2]
####################################################################################################
(117, 5)
keep_x = [563.2262, 560.0, 561.251, 560.5673],  mean = 561 
keep_y = [469.10074, 468.99686, 468.0, 469.83273],  mean = 468 
idx_i_j =  [24, 64, 112, 0]
vertex_idx =  [1, 2, 0, 3]
####################################################

In [ ]:
import pandas as pd
x = res1[0]
df = pd.DataFrame(x[x[:, 4] > 0.5])
df.sort_values(by=[2]).iloc[5:20]
# 54 index of AB l u 293, 175
# 62 index of AB r d 293, 227

#  60 top left
#60 62 54

0           1           2           3         4
46   -0.250851  228.580963   78.023727  286.501556  0.800823
48   -0.330349  569.600159   78.037292  628.487366  0.795830
45   -0.566307  627.015259   78.074615  687.526733  0.800880
60   -0.300343  166.489777   78.427979  229.551117  0.577561
14   75.880646  342.271515  293.861877  399.613495  0.855955
12   75.800255  286.219360  294.110229  342.418823  0.859902
22   75.923439  571.358704  294.539032  626.678284  0.847705
33   75.263840  458.408295  294.785095  511.845459  0.831765
43   75.030029  400.211914  295.070831  457.177917  0.811991
62   76.336823  168.201935  295.248840  227.959595  0.547779
41   74.186142  230.387253  295.573608  285.063965  0.819956
21   74.306137  514.123535  295.640808  570.270630  0.847859
44   74.294395  628.826294  295.776855  685.369019  0.803283
54  293.022034  175.378555  509.624390  227.734421  0.754425
0   292.159973  286.068909  510.660583  341.723938  0.889665

In [ ]:
import numpy as np
x = _res_algo2[0]
x[x[:, 4] < 0.59 ]


array([[0.0000000e+00, 1.6700000e+02, 7.6000000e+01, 2.2800000e+02,
        5.7756060e-01],
       [1.1570000e+03, 1.6800000e+02, 1.2800000e+03, 2.2800000e+02,
        5.7699066e-01],
       [7.6000000e+01, 1.6900000e+02, 2.9200000e+02, 2.2800000e+02,
        5.4777879e-01]], dtype=float32)

In [ ]:
_res_algo2[0]
0 ... 62

array([[2.9200000e+02, 2.8500000e+02, 5.0800000e+02, 3.4200000e+02,
        8.8966483e-01],
       [2.9200000e+02, 3.4200000e+02, 5.0900000e+02, 3.9900000e+02,
        8.8530356e-01],
       [2.9200000e+02, 5.7000000e+02, 5.0900000e+02, 6.2700000e+02,
        8.7157291e-01],
       [7.2400000e+02, 6.2700000e+02, 9.4100000e+02, 6.8300000e+02,
        8.7079078e-01],
       [7.2500000e+02, 3.4200000e+02, 9.4100000e+02, 3.9900000e+02,
        8.7057877e-01],
       [2.9200000e+02, 5.1300000e+02, 5.0900000e+02, 5.7000000e+02,
        8.7017834e-01],
       [2.9200000e+02, 3.9900000e+02, 5.0900000e+02, 4.5600000e+02,
        8.6887890e-01],
       [7.2500000e+02, 2.8500000e+02, 9.4100000e+02, 3.4200000e+02,
        8.6323601e-01],
       [5.0800000e+02, 2.8500000e+02, 7.2500000e+02, 3.4200000e+02,
        8.6301512e-01],
       [2.9200000e+02, 4.5600000e+02, 5.0900000e+02, 5.1300000e+02,
        8.6277997e-01],
       [5.0900000e+02, 3.4200000e+02, 7.2500000e+02, 3.9900000e+02,
        8.62

In [ ]:

# Specify the path to model config and checkpoint file
config_file = '/home/aiarhipov/centernet/exps/19_eval/config.py'
checkpoint_file = '/home/aiarhipov/centernet/exps/19_eval/epoch60_resnet34_batch2.pth'

# build the model from a config file and a checkpoint file
model = init_detector(config_file, checkpoint_file, device='cuda:0')

# test a single image and show the results
# img_path = '/home/aiarhipov/centernet/imgs/0c38706d33642e2c68389688009a4c3958601299.jpg'  # or img = mmcv.imread(img), which will only load it once
img_path = '/home/aiarhipov/centernet/imgs/0d995a743dccbda88af4955cd07ab5bf3b8b663e.jpg'  # or img = mmcv.imread(img), which will only load it once
res = inference_detector(model, img_path)
result = res
# visualize the results in a new window
# model.show_result(img, result)
# or save the visualization results to image files
# model.show_result(img, result, out_file='result.jpg')
threshold = 0.5
show_result_pyplot(model, img_path, res, score_thr = threshold, out_file = "/home/aiarhipov/centernet/imgs/output.jpg")

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import MinMaxScaler


boxes = result[0]
confident_boxes = boxes[boxes[:, 4] > threshold]
count_confident_boxes = confident_boxes.shape[0]

updated_confident_boxes=confident_boxes

X = confident_boxes[:, [0, 2]].flatten()
Y = confident_boxes[:, [1, 3]].flatten()

X_scaled = MinMaxScaler().fit_transform(X.reshape((-1, 1)))
Y_scaled = MinMaxScaler().fit_transform(Y.reshape((-1, 1)))

min_samples = int(np.sqrt(count_confident_boxes) / 2)
print("min_samples = ", min_samples)
clustering_X = DBSCAN(eps=0.01, min_samples=min_samples).fit_predict(X_scaled)
clustering_Y = DBSCAN(eps=0.01, min_samples=min_samples).fit_predict(Y_scaled)

labels_X = set(clustering_X)
labels_Y = set(clustering_Y)


img = Image.open(img_path)
draw = ImageDraw.Draw(img)
colors = [(255,0,0), (255,255,0), (255,0,255)]
width = 5

x_correct = []
y_correct = []
for x in labels_X:
    if x != -1:
        x_mean = int(np.mean(X[np.array(clustering_X) == x]))
        # print(f"x_label = {x}, x_mean = {x_mean}")
        x_correct.append(x_mean)
    
for y in labels_Y:
    if y != -1:
        y_mean = int(np.mean(Y[np.array(clustering_Y) == y]))
        # print(f"y_label = {y}, y_mean = {y_mean}")
        y_correct.append(y_mean)

for x in labels_X:
    if x != -1:
        x_mean = int(np.mean(X[np.array(clustering_X) == x]))
        endpoints = (x_mean, max(y_correct)), (x_mean, min(y_correct))
        draw.line(endpoints, fill=colors[0], width=width)
for y in labels_Y:
    if y != -1:
        y_mean = int(np.mean(Y[np.array(clustering_Y) == y]))
        endpoints = (max(x_correct), y_mean), (min(x_correct), y_mean)
        draw.line(endpoints, fill=colors[0], width=width)
    
print(f"sorted_confident_x = {sorted(x_correct)}")
print(f"sorted_confident_y = {sorted(y_correct)}")

img.save("/home/aiarhipov/centernet/imgs/output_lines.jpg")

min_samples =  3
sorted_confident_x = [0, 76, 293, 509, 725, 941, 1157, 1280]
sorted_confident_y = [170, 229, 285, 342, 399, 457, 513, 570, 628, 685]


In [ ]:
import numpy as np
X = np.array([[1, 2, 3], [4, 5, 6]])
for x in X:
    print(x)

[1 2 3]
[4 5 6]
